### ISSUE TITLE
Breaking changes in 6.0.3 for ListObjectsAsync

### ISSUE THREAD

**Issue by RobSlgm** [minio/minio-dotnet#1115]
With 6.0.3 a call of `client.ListObjectsAsync(args, ct)`fails to compile. It compiled and worked with 6.0.2.

#1049 introduces a `Minio.ApiEndpoints.CompatibilityExtensions` which maps some ListObjectsAsync calls to the new ListObjectsEnumAsync. The calls with an `CancellationToken` are missing.

**Comment by ebozduman** [comment]
looking into it...

**Comment by ramondeklein** [comment]
It was a mistake to add `IObservable<T>` with a cancellation-token in the first place, so you should probably not want to use this. If  you want to cancel an observable, then you should dispose the subscription. Submitted #1116 to bring back the cancellation token.

@RobSlgm Instead of using the cancellation token, I would highly recommend to cancel the subscription instead. That's the proepr solution. Cancellation tokens are meant to be used with async programming (using tasks). When using `IObservable<T>`, then stick with that.

**Comment by harshavardhana** [comment]
Why is this reopened?

**Comment by ebozduman** [comment]
Sorry! It is a mistake.
I did not even realize I've reopened it.
My fingers are not listening to me.
