### ISSUE TITLE
Get/Set Policy equivalent of setting bucket readonly in json

### ISSUE THREAD

**Issue by xmichaelx** [minio/minio-dotnet#262]
Hey, I've recently migrated from Minio.NetCore 1.0.7 to Minio 2.0.6 and I've noticed that there is no longer PolicyType type and now everything is done through json.

I've previously used to set readonly policy on one bucket, what should I modify in the policy I get from the bucket to make it readonly?

And would it be possible to work on json deserialized into classess make changes on it and pass it back in SetPolicy method or are you deliberately not doing it to keep the interaction raw and not introduce dependency on NewtonSoft.Json?

**Comment by harshavardhana** [comment]
https://gist.github.com/harshavardhana/3c3864bfdb917cbe0fe1b095bc7fa54a here is a list of canned policies which can be used.

We are deliberately doing it because canned policies didn't make much sense from an SDK point of view and requirements for other complex situations have arrived which canned policy does not allow. Since users wanted quite a few variations in their policy document it was natural to just provide a RAW string so that you can construct whatever policy you feel like. 

The construction of such policies was moved out, treated as application responsibility.  So you can keep of a list of canned policies in your application which correspond to a JSON as written in the above-referenced link.

**Comment by xmichaelx** [comment]
Thank you for quick response :)
