### ISSUE TITLE
.Net Framework API Controller cannot get response.

### ISSUE THREAD

**Issue by ferdinandhuang** [minio/minio-dotnet#295]
When I try to use Minio Client in my .Net framework project, it worked in Console project, but it cannot receive any response in WebAPI Controller.
I try to figure out what happened and i located at 
MinioClient.cs :  line 357

`IRestResponse response = await this.restClient.ExecuteTaskAsync(request,cancellationToken);`

When I replace **await** to **Result**, it can worked. If i debug into the function, it also can receive response, but it hung up if I use **F10** to step over the function.

I don't know what happend, is that a bug?

**Comment by poornas** [comment]
It is very well possible that you need to use .Wait() on your invocation of API call. If that doesn't solve your issue, please share a sample project that we can try out

**Comment by ferdinandhuang** [comment]
It doesn't work for .Wait() , it also hung up.
The test code just like this in a new webapi project's controller, and i think it's easy to reproduction:
`
            var minio = new MinioClient(minioUrl, key, secret);

            var buckets = minio.ListBucketsAsync();
            buckets.Wait();
            return Ok(buckets);
`

**Comment by poornas** [comment]
@ferdinandhuang, you might want to check this [example](https://docs.microsoft.com/en-us/aspnet/web-api/overview/advanced/calling-a-web-api-from-a-net-client) on using async calls within your web api controller - since ListBucketsAsync() is an async method, you will need to call this within an async method or if in a static method - use RunAsync().GetAwaiter().GetResult(); as in the example. I am afraid we can't help with debugger behavior here, which seems to be the issue rather than SDK not working correctly

**Comment by poornas** [comment]
@ferdinandhuang , is this issue resolved for you?

**Comment by ferdinandhuang** [comment]
> @ferdinandhuang , is this issue resolved for you?

I'm sorry for it still not woring, so i chang the code to my project.

But it work will in .net core project.

**Comment by kannappanr** [comment]
Closing this issue as stale.
