### ISSUE TITLE
System.NullReferenceException in Obsolete Constructor

### ISSUE THREAD

**Issue by gnulp** [minio/minio-dotnet#679]
NullReferenceException  in MinioClient.cs in Constructor
public MinioClient(string endpoint, string accessKey = "",
        string secretKey = "", string region = "", string sessionToken = "")
in Line 139:
HTTPClient.DefaultRequestHeaders.TryAddWithoutValidation("User-Agent", FullUserAgent);

I guess there is a missing call to the baseconstructor ": this()" which initializes HTTPClient.

**Comment by ebozduman** [comment]
@gnulp 

That is a deprecated/obsolete method. Since it is obsolete, we moved on and it has not been modified to bring it uptodate.

Here is an example of the current constructor:
```
            new MinioClient()
                .WithEndpoint(endpoint)
                .WithCredentials(accessKey, secretKey)
                .WithRegion(region)
                .WithHttpClient(httpClient)
                .WithSessionToken(sessionToken)
                .WithSSL()
                .Build();
```

There is a known issue, [#682](https://github.com/minio/minio-dotnet/issues/682), about the references to deprecated/obsolete methods in our documentation, which will be addressed soon.
Closing as `"won't fix"`.
If you have a compelling reason to use the deprecated `MinioClient` constructor instead of using the supported format, please reopen the issue and let us know why you need it.
