### ISSUE TITLE
net462 minio putobject  objectkey Include parentheses "()" error

### ISSUE THREAD

**Issue by kaanid** [minio/minio-dotnet#708]
errResponse.Code: "SignatureDoesNotMatch"
errResponse.Message: The request signature we calculated does not match the signature you provided. Check your key and signing method.

I found that,net462(uri.AbsolutePath) is different from net6.0(uri.AbsolutePath)

`
Uri uri = new Uri($"http://www.a.com/a%28%E5%A5%BD%29/index.html");
`

1. net462 AbsolutePath: /a(%E5%A5%BD)/index.html
2. net48 AbsolutePath: /a%28%E5%A5%BD%29/index.html
3. net6.0 AbsolutePath: /a%28%E5%A5%BD%29/index.html

Please upgrade to net48.

**Comment by martijn00** [comment]
Fixed in https://github.com/minio/minio-dotnet/pull/732

**Comment by martijn00** [comment]
@ebozduman this can be closed i think

**Comment by martijn00** [comment]
@ebozduman please close this one

**Comment by ebozduman** [comment]
closed...

**Comment by ebozduman** [comment]
@kaanid 
By the way, the issue you see looks like the automatic Uri encoding problem which happens for some special characters.
I believe, this has been addressed in 5.0 and fwd.
So, my point is you may want to move to net6.0 at least, as net5.0 is EOL'ed or put on end of support since May 10, 2022.
