### ISSUE TITLE
How do I obtain the address of an online file？

### ISSUE THREAD

**Issue by andyfan1094** [minio/minio-dotnet#721]
want to get the online address of a picture or video, how to display it directly in HTML

**Comment by Sergey-Terekhin** [comment]
What do you mean? 
If you store file in MinIO and know its path (bucket + location inside bucket), then you can use `MinioClient->PresignedGetObjectAsync` function to get full url of the stored file which can be shown on the page or used to download object. 
If you want to search file in MinIO, then you have to use functions like `ListBuckets` and `ListObjects`

**Comment by martijn00** [comment]
@ebozduman this one doesn't seem valid to me. Can you close it?

**Comment by ebozduman** [comment]
@andyfan1094 ,

If you would like to find an object stored in MinIO, either because you know somebody else put the object you are looking for and you don't know the location or simply you forgot where you put it, then the best is to use MinIO Client, ["mc", command line utility](https://min.io/docs/minio/linux/reference/minio-mc.html) to find the object's location. 

Please check the "mc find" command and refer the doc above or run `mc find --help` command in your terminal to get its help/man page.
